workflows:
  ios-build:
    name: BearCave iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    # TRIGGER: Build automatically on push to main
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    
    integrations:
      app_store_connect: Codemagic CI/CD
    
    environment:
      ios_signing:
        provisioning_profiles:
          - App Store Profile
        certificates:
          - Distribution Certificate
      
      groups:
        - ios_config  # Contains APP_STORE_APP_ID
      
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      
      node: 20
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build
      
      - name: Sync Capacitor to iOS
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true  # For beta testing
        # submit_to_app_store: true  # Uncomment when ready for production release

  android-build:
    name: BearCave Android Build
    max_build_duration: 120
    instance_type: linux_x2
    
    environment:
      android_signing:
        - bearcave_keystore  # You'll upload this in Codemagic UI
      
      vars:
        PACKAGE_NAME: "com.deepdenebears.bearcave"
      
      node: 20
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build
      
      - name: Update Capacitor config
        script: |
          sed -i 's|url: .*|url: "https://your-app.replit.app",|g' capacitor.config.ts
      
      - name: Sync Capacitor to Android
        script: |
          npx cap sync android
      
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      
      - name: Build Android release
        script: |
          cd android
          ./gradlew bundleRelease
    
    artifacts:
      - android/app/build/outputs/**/*.aab
    
    # Uncomment publishing section after you set up Google Play Console
    # publishing:
    #   google_play:
    #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #     track: internal  # or: alpha, beta, production
